<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezwebin_democontent",
                     "development" => false,
                     "summary" => "Home, News and Events, Products, Partner, Community, Knowledge Base, Company",
                     "description" => "This package contains the following nodes :\nHome - subtree\nNews and Events - subtree\nProducts - subtree\nPartner - subtree\nCommunity - subtree\nKnowledge Base - subtree\nCompany - subtree\n",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.2.0rc2",
                                           "named-version" => "4.2" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1163689610",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1163689610",
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array( "564a9852c167d1ec95d820df7eb8a44f" => array( "original-path" => "var/storage/images/products/software/os_type_i/1139-1-eng-GB/os_type_i.jpg",
                                                                                               "package-path" => "simplefiles/99c9ae32.jpg" ),
                                                  "e394f4438f2937e0a712cf48fe59febb" => array( "original-path" => "var/storage/images/products/boxes/cd_dvd_box_i/1123-1-eng-GB/cd_dvd_box_i.jpg",
                                                                                               "package-path" => "simplefiles/d6088fb8.jpg" ),
                                                  "3e64c1ff7bcabffce3fee7505a9ffe05" => array( "original-path" => "var/storage/images/products/boxes/cd_dvd_box_ii/1131-5-eng-GB/cd_dvd_box_ii.jpg",
                                                                                               "package-path" => "simplefiles/91b3539c.jpg" ),
                                                  "bfd3b9bbc47b130f01e6176f0a75c88f" => array( "original-path" => "var/storage/images/products/boxes/cd_dvd_box_iii/1147-12-eng-GB/cd_dvd_box_iii.jpg",
                                                                                               "package-path" => "simplefiles/feb6c0d6.jpg" ),
                                                  "6f1ca5f47040a878cae623ce3ab2a3f8" => array( "original-path" => "var/storage/images/partners/partner_news/pellentesque_quam_mauris/1983-1-eng-GB/pellentesque_quam_mauris.jpg",
                                                                                               "package-path" => "simplefiles/c9b86255.jpg" ),
                                                  "c953c6d18ab0e7386f1e9b33132c699b" => array( "original-path" => "var/storage/images/partners/partner_news/penatibus_et_magnis_dis/2027-1-eng-GB/penatibus_et_magnis_dis.jpg",
                                                                                               "package-path" => "simplefiles/f60ab7d0.jpg" ),
                                                  "999b778d49ac1869797f1a6c7e4a37b3" => array( "original-path" => "var/storage/images/partners/news/curabitur_hendrerit_dignissim/1994-1-eng-GB/curabitur_hendrerit_dignissim.jpg",
                                                                                               "package-path" => "simplefiles/cf429c58.jpg" ),
                                                  "f3e553cc9a2547c8589e63eab3de129c" => array( "original-path" => "var/storage/images/partners/news/proin_condimentum_risus/2005-1-eng-GB/proin_condimentum_risus.jpg",
                                                                                               "package-path" => "simplefiles/193dd1e3.jpg" ),
                                                  "1b47e63abb417dcdf7f1f3ae652e374a" => array( "original-path" => "var/storage/images/partners/news/morbi_tristique_senectus/2016-1-eng-GB/morbi_tristique_senectus.jpg",
                                                                                               "package-path" => "simplefiles/60f6ca07.jpg" ),
                                                  "94feb3e7dfb8cdc6ae3cc3968ef4d99f" => array( "original-path" => "var/storage/images/partners/partners/neque_orci_malesuada_felis/2038-1-eng-GB/neque_orci_malesuada_felis.jpg",
                                                                                               "package-path" => "simplefiles/2eb3cd21.jpg" ),
                                                  "8eec2ae765a58f9b9bb7e5bc43039a4f" => array( "original-path" => "var/storage/images/solutions/web_publishing/fusce_sagittis_sagittis/1428-1-eng-GB/fusce_sagittis_sagittis.jpg",
                                                                                               "package-path" => "simplefiles/f24d6bcd.jpg" ),
                                                  "964918b69ab0954df8e9d6f7adf66321" => array( "original-path" => "var/storage/images/solutions/web_publishing/etiam_posuere_sodales_arcu/1439-1-eng-GB/etiam_posuere_sodales_arcu.jpg",
                                                                                               "package-path" => "simplefiles/281497ce.jpg" ),
                                                  "4896af0dbfe88c4281c2b404904917ea" => array( "original-path" => "var/storage/images/solutions/web_publishing/in_hac_habitasse_platea/1461-3-eng-GB/in_hac_habitasse_platea.jpg",
                                                                                               "package-path" => "simplefiles/255df1c9.jpg" ),
                                                  "35c37a7ba41e46b755006a924bb5b526" => array( "original-path" => "var/storage/images/training/professional_workshops/etiam_sodales_mauris/1843-1-eng-GB/etiam_sodales_mauris.jpg",
                                                                                               "package-path" => "simplefiles/ec2336c5.jpg" ),
                                                  "2d60a969f5caf8a6871c93a77a81347e" => array( "original-path" => "var/storage/images/training/professional_workshops/class_aptent_taciti/1854-1-eng-GB/class_aptent_taciti.jpg",
                                                                                               "package-path" => "simplefiles/22546794.jpg" ),
                                                  "b7d201c58fadf31edd9f0ca4788517ce" => array( "original-path" => "var/storage/images/training/professional_workshops/duis_auctor_vehicula_erat/1876-2-eng-GB/duis_auctor_vehicula_erat.jpg",
                                                                                               "package-path" => "simplefiles/599395bf.jpg" ),
                                                  "5b47bda697fb9d098bb81e99bf222fa8" => array( "original-path" => "var/storage/images/support/books/aliquam_pulvinar_suscipit_tellus/1972-1-eng-GB/aliquam_pulvinar_suscipit_tellus.jpg",
                                                                                               "package-path" => "simplefiles/e6266052.jpg" ),
                                                  "82141e57eb139ddac809a6b1e573605e" => array( "original-path" => "var/storage/images/company/contact/morbi_neque/1646-1-eng-GB/morbi_neque.jpg",
                                                                                               "package-path" => "simplefiles/d1ce478e.jpg" ),
                                                  "5edd572bd980f684b2e3aa61fc85fceb" => array( "original-path" => "var/storage/images/company/company_banner/1904-3-eng-GB/company_banner.jpg",
                                                                                               "package-path" => "simplefiles/709770af.jpg" ),
                                                  "e2a95a056702cf41379dcf25be043d1c" => array( "original-path" => "var/storage/images/company/news/lyon-a-culture-of-partnership/1028-1-eng-US/Lyon-a-culture-of-partnership.jpg",
                                                                                               "package-path" => "simplefiles/25a010fb.jpg" ),
                                                  "b06750127eb2d3f3562e3f12e4b82510" => array( "original-path" => "var/storage/images/company/news/lyon-a-land-of-projects/1039-2-eng-US/Lyon-a-land-of-projects.jpg",
                                                                                               "package-path" => "simplefiles/135200c8.jpg" ),
                                                  "36158ea863de6f7cfabdbc629eb6b7ef" => array( "original-path" => "var/storage/images/company/news/lyon-a-widely-envied-quality-of-life/1050-3-eng-US/Lyon-a-widely-envied-quality-of-life.jpg",
                                                                                               "package-path" => "simplefiles/3a982ce8.jpg" ),
                                                  "b79bd4c7132377f7f740a41345277ddc" => array( "original-path" => "var/storage/images/company/news/lyon-encourages-talents/1061-2-eng-US/Lyon-encourages-talents.jpg",
                                                                                               "package-path" => "simplefiles/2d994649.jpg" ),
                                                  "aff2bf6b520c711124f2a63ba4409988" => array( "original-path" => "var/storage/images/company/news/lyon-more-for-your-money/1072-2-eng-US/Lyon-more-for-your-money.jpg",
                                                                                               "package-path" => "simplefiles/a540854b.jpg" ),
                                                  "06bf5b1fce69a36703e83b62f03eb3eb" => array( "original-path" => "var/storage/images/company/news/lyon-world-class-facilities/1083-2-eng-US/Lyon-world-class-facilities.jpg",
                                                                                               "package-path" => "simplefiles/2e32171a.jpg" ),
                                                  "39511292c57d952ac65563fc5bcb31f6" => array( "original-path" => "var/storage/images/company/news/lyon-puts-europe-at-your-doorstep/1094-2-eng-US/Lyon-puts-Europe-at-your-doorstep.jpg",
                                                                                               "package-path" => "simplefiles/0408cd0f.jpg" ),
                                                  "38826f36525168f843acf4b2728a0ca3" => array( "original-path" => "var/storage/images/company/news/lyon-the-testing-ground/1105-3-eng-US/Lyon-the-testing-ground.jpg",
                                                                                               "package-path" => "simplefiles/2e9ba3f9.jpg" ),
                                                  "d80452bff05cbac12a40fe582858b6f0" => array( "original-path" => "var/storage/images/company/news/lyon-attracts-world-leaders/1116-2-eng-US/Lyon-attracts-world-leaders.jpg",
                                                                                               "package-path" => "simplefiles/d5dd7286.jpg" ),
                                                  "ded458ff1df4a9c856f8d512760a8b56" => array( "original-path" => "var/storage/images/company/news/lyon,-an-european-metropolis/1127-3-eng-US/Lyon,-an-European-metropolis.jpg",
                                                                                               "package-path" => "simplefiles/74f6f397.jpg" ),
                                                  "3ba7d9326f877774c7444634cdab7d89" => array( "original-path" => "var/storage/images/community/lyon-pictures/lyon/1138-1-eng-US/Lyon.jpg",
                                                                                               "package-path" => "simplefiles/2bb67da5.jpg" ),
                                                  "4d63cb263daac713e79fc69bf315932c" => array( "original-path" => "var/storage/images/community/lyon-pictures/grand-lyon/1142-1-eng-US/Grand-Lyon.jpg",
                                                                                               "package-path" => "simplefiles/a99e707a.jpg" ),
                                                  "2f4f07da61215caf94307a3b6b3e3373" => array( "original-path" => "var/storage/images/community/lyon-pictures/lyon-river/1146-1-eng-US/Lyon-River.jpg",
                                                                                               "package-path" => "simplefiles/0472b577.jpg" ),
                                                  "0dd183a2c02c7f5c91eb8ef46ddbff47" => array( "original-path" => "var/storage/images/community/lyon-pictures/castle-on-the-hill/1150-1-eng-US/Castle-on-the-hill.jpg",
                                                                                               "package-path" => "simplefiles/97e05f2f.jpg" ),
                                                  "5e6fa5a245cee307ea4173573d71170a" => array( "original-path" => "var/storage/images/company/news/separate-content-design-in-ez-publish/separation_of_content_and_design/1230-1-eng-GB/separation_of_content_and_design.png",
                                                                                               "package-path" => "simplefiles/4caff6ac.png" ),
                                                  "75b7a914c933f88b8c177d0a960d7c96" => array( "original-path" => "var/storage/images/company/news/separate-content-design-in-ez-publish/1142-3-eng-GB/Separate-content-design-in-eZ-Publish.jpg",
                                                                                               "package-path" => "simplefiles/f6278d0f.jpg" ),
                                                  "48bb9c5e332ee04f1fbb2ff36d34916a" => array( "original-path" => "var/storage/images/company/news/how-to-develop-with-ez-publish/datatypes_attributes_content_class_and_objects_large/1254-1-eng-GB/datatypes_attributes_content_class_and_objects_large.png",
                                                                                               "package-path" => "simplefiles/17180389.png" ),
                                                  "efa015b1e5fcab65c113ca733612337a" => array( "original-path" => "var/storage/images/company/news/how-to-develop-with-ez-publish/site_style_large/1258-1-eng-GB/site_style_large.png",
                                                                                               "package-path" => "simplefiles/e7f4a5ee.png" ),
                                                  "20196faed28c0f34c21c1d57511b9cd2" => array( "original-path" => "var/storage/images/company/news/how-to-develop-with-ez-publish/1246-2-eng-GB/How-to-develop-with-eZ-Publish.png",
                                                                                               "package-path" => "simplefiles/dad96df4.png" ),
                                                  "0a74131248f2c20756e5ce44e16d0c21" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/1194-1-eng-GB/How-to-manage-eZ-Publish.png",
                                                                                               "package-path" => "simplefiles/bb8e1919.png" ),
                                                  "5bb50a0c29ae62fded4a1dda7d12047d" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/usermanagement_large/1202-1-eng-GB/usermanagement_large.png",
                                                                                               "package-path" => "simplefiles/0a92d82d.png" ),
                                                  "cade8da3abdfe9963a44e1f7f23f1cf6" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/workflow_large/1206-1-eng-GB/workflow_large.png",
                                                                                               "package-path" => "simplefiles/6b92d0e1.png" ),
                                                  "1f383098b7247d1ebef001071a6e13df" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/versioning_large/1210-1-eng-GB/versioning_large.png",
                                                                                               "package-path" => "simplefiles/7976c96e.png" ),
                                                  "6c4dc92b04bc8afbd205dbd7d4dc933e" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/datatypes_attributes_content_class_and_objects_large/1214-1-eng-GB/datatypes_attributes_content_class_and_objects_large.png",
                                                                                               "package-path" => "simplefiles/e5aae376.png" ),
                                                  "afd85b88f502c2378d025c0d49153b2b" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/multiple_location_large/1218-1-eng-GB/multiple_location_large.png",
                                                                                               "package-path" => "simplefiles/737ced2d.png" ),
                                                  "3d6aa9b7fdf96df41f35873b66fe117e" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/multisite_deployment_large/1222-1-eng-GB/multisite_deployment_large.png",
                                                                                               "package-path" => "simplefiles/8888be5e.png" ),
                                                  "c5b6d5c3ccb3114d8c8f98e684670948" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/seo_large/1226-1-eng-GB/seo_large.png",
                                                                                               "package-path" => "simplefiles/c70f6571.png" ),
                                                  "a883b99500e648d6cdc887b94751de6e" => array( "original-path" => "var/storage/images/company/news/how-to-manage-ez-publish/admin_site_large/1238-1-eng-GB/admin_site_large.png",
                                                                                               "package-path" => "simplefiles/fd0b0e70.png" ),
                                                  "0ca7c9f4b5a8ede5bd4651ceab8a56db" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/1154-1-eng-GB/How-to-use-eZ-Publish.png",
                                                                                               "package-path" => "simplefiles/38da926f.png" ),
                                                  "f7446f3f2d242816309f88305f27941a" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/openoffice_import_large/1162-1-eng-GB/openoffice_import_large.png",
                                                                                               "package-path" => "simplefiles/c6bfbab1.png" ),
                                                  "6284948f624235b2c039932ffdef0ed4" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/translation_large/1166-1-eng-GB/translation_large.png",
                                                                                               "package-path" => "simplefiles/be65e663.png" ),
                                                  "2b445be70c65528a899a409202381206" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/multiupload_large/1170-1-eng-GB/multiupload_large.png",
                                                                                               "package-path" => "simplefiles/1e95ab58.png" ),
                                                  "5dfaeda190ed707bec3c96d889142918" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/gallery_large/1174-1-eng-GB/gallery_large.png",
                                                                                               "package-path" => "simplefiles/f7425e03.png" ),
                                                  "ba06665123876e00b9c262a9a4f1cc3c" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/search_result_large/1186-1-eng-GB/search_result_large.png",
                                                                                               "package-path" => "simplefiles/53f9818c.png" ),
                                                  "00070e011835c04d473bd03bbcecaa8f" => array( "original-path" => "var/storage/images/company/news/how-to-use-ez-publish/ez_tool_bar_large/1234-1-eng-GB/ez_tool_bar_large.png",
                                                                                               "package-path" => "simplefiles/c36d0aa5.png" ),
                                                  "fc81f187da1ac466209e0e23b8d6d09c" => array( "original-path" => "var/storage/images/media/images/quicktime_large/1178-1-eng-GB/quicktime_large.png",
                                                                                               "package-path" => "simplefiles/839e42d6.png" ),
                                                  "31b448d1f44f0ef04c55efa67a9b71d9" => array( "original-path" => "var/storage/images/media/images/web_2_0_large/1182-1-eng-GB/web_2_0_large.png",
                                                                                               "package-path" => "simplefiles/febd930d.png" ),
                                                  "784eb7c6fc4f18e304b15fdbf30ff9b3" => array( "original-path" => "var/storage/images/community/pictures/ez-conference-2009/719-2-eng-GB/eZ-Conference-2009.jpg",
                                                                                               "package-path" => "simplefiles/d2bf73b7.jpg" ),
                                                  "585c8b1df2e3515f191c6546a3bcba59" => array( "original-path" => "var/storage/images/community/pictures/ez-awards/723-2-eng-GB/eZ-Awards.jpg",
                                                                                               "package-path" => "simplefiles/de459208.jpg" ),
                                                  "194f2a35e1981f90ad5b2dfab0d16ef6" => array( "original-path" => "var/storage/images/community/pictures/digital-media-award/727-2-eng-GB/Digital-Media-Award.jpg",
                                                                                               "package-path" => "simplefiles/79c1cace.jpg" ),
                                                  "35f621eb4988eb0438ab8fb7ac136b08" => array( "original-path" => "var/storage/images/community/pictures/champs-elysees/731-2-eng-GB/Champs-Elysees.jpg",
                                                                                               "package-path" => "simplefiles/6c821f81.jpg" ),
                                                  "bfcabd2e4739e85cc485e60eaa1a15de" => array( "original-path" => "var/storage/images/community/pictures/developer-session/1110-1-eng-GB/Developer-session.jpg",
                                                                                               "package-path" => "simplefiles/de81bbce.jpg" ),
                                                  "53569d8cd87245c45da568420285b212" => array( "original-path" => "var/storage/images/community/pictures/community-talk/1114-1-eng-GB/Community-talk.jpg",
                                                                                               "package-path" => "simplefiles/ecfae435.jpg" ),
                                                  "6745ca5538561e095cc0d085cc859d50" => array( "original-path" => "var/storage/images/community/pictures/partner-of-the-year-2009/1118-1-eng-GB/Partner-of-the-year-2009.jpg",
                                                                                               "package-path" => "simplefiles/cf770d0f.jpg" ),
                                                  "9c4e43191addfe73fd9b7fd7b0e54c9d" => array( "original-path" => "var/storage/images/community/pictures/ez-awards2/1122-1-eng-GB/eZ-Awards.jpg",
                                                                                               "package-path" => "simplefiles/28bbcd90.jpg" ) ),
                     "version-number" => "1.5",
                     "release-number" => "0rc2",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentobject",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "type" => "ezcontentobject",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages";
?>
