{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<p{section show=ne($classification|trim,'')} class="{$classification|wash}"{/section}>
{if $content|trim|eq("")}&nbsp;{else}{$content}{/if}
</p>
